module.exports = [
"There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind.",
"Often when you think you're at the end of something, you're at the beginning of something else.",
"All of us have special ones who have loved us into being",
"Imagine what our real neighborhoods would be like if each of us offered . . . just one kind word to another person.",
"You make each day a special day. You know how, by just your being you.",
"Transitions are almost always signs of growth, but they can bring feelings of loss. To get somewhere new, we may have to leave somewhere else behind.",
"The greatest gift you ever give is your honest self.",
"A love of learning has a lot to do with learning that we are loved.",
"The older I get, the more convinced I am that the space between people who are trying their best to understand each other is hallowed ground.",
"I feel so strongly that deep and simple is far more essential than shallow and complex.",
"Knowing that we can be loved exactly as we are gives us all the best opportunity for growing into the healthiest of people.",
"Anyone who does anything to help a child in his life is a hero to me.",
"Try your best to make goodness attractive. That's one of the toughest assignments you'll ever be given.",
"The best teacher in the world is someone who loves what he or she does, and just loves it in front of you.",
"Honesty is often very hard. The truth is often painful. But the freedom it can bring is worth the trying.",
"We Don't always succeed in what we try, certainly not by the world's standards, but I think you'll find it's the willingness to keep trying that matters most.",
"Life is deep and simple, and what our society gives us is shallow and complicated.",
"Play is often talked about as if it were a relief from serious learning. But for children play is serious learning. Play is really the work of childhood.",
"Love begins with listening.",
"Often, problems are knots with many strands, and looking at those strands can make a problem seem different.",
"You know, you don't have to look like everybody else to be acceptable and to feel acceptable.",
"In times of stress, the best thing we can do for each other is to listen with our ears and our hearts and to be assured that our questions are just as important as our answers.",
"It would have been sad for me to spend my life just trying to superimpose stuff on people rather than trying to encourage them to look within themselves for what's of value.",
"Who we are in the present includes who we were in the past.",
"Attitudes are caught, not taught.",
"The connections we make in the course of a life--maybe that's what heaven is.",
"How many times have you noticed that it's the little quiet moments in the midst of life that seem to give the rest extra-special meaning?",
"Real strength has to do with helping others."

]
